/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RecipesIdImport } from './routes/$recipesId'

// Create Virtual Routes

const RecipesLazyImport = createFileRoute('/recipes')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const RecipesLazyRoute = RecipesLazyImport.update({
  path: '/recipes',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/recipes.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const RecipesIdRoute = RecipesIdImport.update({
  path: '/$recipesId',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/$recipesId.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/$recipesId': {
      id: '/$recipesId'
      path: '/$recipesId'
      fullPath: '/$recipesId'
      preLoaderRoute: typeof RecipesIdImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  RecipesIdRoute,
  AboutLazyRoute,
  RecipesLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$recipesId",
        "/about",
        "/recipes"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/$recipesId": {
      "filePath": "$recipesId.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/recipes": {
      "filePath": "recipes.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
